---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: manager-role
rules:
- apiGroups:
  - batch.zhewtang.github.io
  resources:
  - sequentialjobs
  verbs:
  - create
  - delete
  - get
  - list
  - patch
  - update
  - watch
- apiGroups:
  - batch.zhewtang.github.io
  resources:
  - sequentialjobs/finalizers
  verbs:
  - update
- apiGroups:
  - batch.zhewtang.github.io
  resources:
  - sequentialjobs/status
  verbs:
  - get
  - patch
  - update
