# permissions for end users to view sequentialjobs.
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  labels:
    app.kubernetes.io/name: clusterrole
    app.kubernetes.io/instance: sequentialjob-viewer-role
    app.kubernetes.io/component: rbac
    app.kubernetes.io/created-by: k8s-sequential-deployment-opeartor-v2
    app.kubernetes.io/part-of: k8s-sequential-deployment-opeartor-v2
    app.kubernetes.io/managed-by: kustomize
  name: sequentialjob-viewer-role
rules:
- apiGroups:
  - batch.zhewtang.github.io
  resources:
  - sequentialjobs
  verbs:
  - get
  - list
  - watch
- apiGroups:
  - batch.zhewtang.github.io
  resources:
  - sequentialjobs/status
  verbs:
  - get
